name: Run VM tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
jobs:
  vm-tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest # x86
            system: "x86_64-linux"
            test: hjem-basic
          - os: ubuntu-22.04-arm # aarch64
            system: "aarch64-linux"
            test: hjem-basic
          - os: ubuntu-latest
            system: "x86_64-linux"
            test: hjem-special-args
          - os: ubuntu-22.04-arm
            system: "aarch64-linux"
            test: hjem-special-args

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            experimental-features = nix-command flakes
            system-features = kvm nixos-test
            allow-import-from-derivation = false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        run: nix build -L .#checks.${{ matrix.system }}.${{ matrix.test }}
